---
title: "UVA_SDS_Text_Mining"
author: "Brian Wright"
date: "May 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(NLP)
library(RColorBrewer)
library(wordcloud)
library(tm)
library(pdftools)
library(ggplot2)
library(extrafont)
font_import()
loadfonts(device = "win")
```

```{r}
UVA_SDS <- readPDF(control=list(text="-layout"))(elem=list(uri="SDS_Proposal.pdf"), language="en")
UVA_text <- UVA_SDS$content
UVA_text <- UVA_text[-c(1:4)]#removing beginning and ending extra text 
UVA_text <- UVA_text[-c(78:104)]

UVASDS_corpus <- Corpus(VectorSource(UVA_text))#creates a usable field of reference, review package information
UVA_clean <- tm_map(UVASDS_corpus, stripWhitespace)
UVA_clean <- tm_map(UVA_clean, removeNumbers)
UVA_clean <- tm_map(UVA_clean, content_transformer(tolower))

UVA_clean <- tm_map(UVA_clean, removeWords, stopwords("english"))#removing stop words

UVA_clean <- tm_map(UVA_clean, removePunctuation)

uva_stopwords <- c("will","uva","dsi","sds","schools","school","data","science","the","and","for","with","...","'s","university","programs","program","student","msds","within") # additional user-defined stop words
                   
                  
UVA_clean <- tm_map(UVA_clean, removeWords, uva_stopwords)

SDS_UVA_Cloud <- wordcloud(UVA_clean, min.freq = 20, max.words=200, random.order=FALSE, scale= c(3, 0.1), colors=brewer.pal(8,"Dark2"))

UVA_tdm <- TermDocumentMatrix(UVA_clean)
head(UVA_tdm_m)
UVA_tdm_m <- as.matrix(UVA_tdm)
v <- sort(rowSums(UVA_tdm_m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)

View(d)
top_words <- read.csv("sds_proposal_top_words.csv")
View(top_words)

barplot(top_words$X189, ylab = "Frequency",names.arg = top_words$faculty, las=2, main = "SDS Proposal Word Frequency",col = "orange")

ggplot(top_words, aes(x=reorder(faculty, X189), y=X189, fill=faculty)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  #scale_fill_manual(values=rep(c("blue","orange"),       ceiling(length(top_words$faculty)/2))[1:length(top_words$faculty)])+
  xlab("Words")+
  ylab("Frequency")+
  labs(fill="Words")+
  ggtitle("SDS Proposal Word Frequency")+
  guides(fill=FALSE)+
  coord_flip()+
  theme(text=element_text(size=15,  family="Comic Sans MS"))+ 
  theme(panel.background = element_rect(fill = "#BFD5E3", colour = "#6D9EC1",
                                size = 2, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"))
  




```

